export const categories = [
  'Phone',
  'Tablet',
  'Laptop',
  'TV',
  'Camera',
  'Audio',
  'Smartwatch',
  'Gaming console',
]

export const electronics = [
  { id: 1, name: 'Iphone 14', categorie: 'Phone' },
  { id: 2, name: 'Iphone 13', categorie: 'Phone' },
  { id: 3, name: 'Samsung Galaxy S23', categorie: 'Phone' },
  { id: 4, name: 'Samsung Galaxy S22', categorie: 'Phone' },
  { id: 5, name: 'Xiaomi Mi 13', categorie: 'Phone' },
  { id: 6, name: 'Xiaomi Redmi Note 12', categorie: 'Phone' },
  { id: 7, name: 'Nokia G22', categorie: 'Phone' },
  { id: 8, name: 'Huawei P50', categorie: 'Phone' },
  { id: 9, name: 'Ipad Pro 12.9', categorie: 'Tablet' },
  { id: 10, name: 'Ipad Air', categorie: 'Tablet' },
  { id: 11, name: 'Samsung Galaxy Tab S8', categorie: 'Tablet' },
  { id: 12, name: 'Samsung Galaxy Tab A8', categorie: 'Tablet' },
  { id: 13, name: 'MacBook Air M2', categorie: 'Laptop' },
  { id: 14, name: 'MacBook Pro 14', categorie: 'Laptop' },
  { id: 15, name: 'Asus ZenBook 14', categorie: 'Laptop' },
  { id: 16, name: 'Asus ROG Strix', categorie: 'Laptop' },
  { id: 17, name: 'MSI GF63', categorie: 'Laptop' },
  { id: 18, name: 'MSI Raider', categorie: 'Laptop' },
  { id: 19, name: 'Dell XPS 13', categorie: 'Laptop' },
  { id: 20, name: 'Dell Inspiron 15', categorie: 'Laptop' },
  { id: 21, name: 'LG OLED TV 55"', categorie: 'TV' },
  { id: 22, name: 'LG NanoCell 65"', categorie: 'TV' },
  { id: 23, name: 'Samsung QLED 75"', categorie: 'TV' },
  { id: 24, name: 'Samsung Crystal UHD 50"', categorie: 'TV' },
  { id: 25, name: 'Sony Bravia 65"', categorie: 'TV' },
  { id: 26, name: 'Sony Bravia 55"', categorie: 'TV' },
  { id: 27, name: 'TCL 6-Series 55"', categorie: 'TV' },
  { id: 28, name: 'TCL 4K 50"', categorie: 'TV' },
  { id: 29, name: 'GoPro Hero 11', categorie: 'Camera' },
  { id: 30, name: 'Canon EOS R6', categorie: 'Camera' },
  { id: 31, name: 'Canon EOS M50', categorie: 'Camera' },
  { id: 32, name: 'Nikon Z6 II', categorie: 'Camera' },
  { id: 33, name: 'Sony Alpha a7 III', categorie: 'Camera' },
  { id: 34, name: 'Sony Alpha a6400', categorie: 'Camera' },
  { id: 35, name: 'Bose QuietComfort 45', categorie: 'Audio' },
  { id: 36, name: 'Bose 700', categorie: 'Audio' },
  { id: 37, name: 'Sony WH-1000XM5', categorie: 'Audio' },
  { id: 38, name: 'Apple AirPods Max', categorie: 'Audio' },
  { id: 39, name: 'JBL Flip 6', categorie: 'Audio' },
  { id: 40, name: 'JBL Charge 5', categorie: 'Audio' },
  { id: 41, name: 'Google Pixel 7', categorie: 'Phone' },
  { id: 42, name: 'Google Pixel 6a', categorie: 'Phone' },
  { id: 43, name: 'OnePlus 11', categorie: 'Phone' },
  { id: 44, name: 'OnePlus Nord 3', categorie: 'Phone' },
  { id: 45, name: 'Motorola Edge 40', categorie: 'Phone' },
  { id: 46, name: 'Motorola Moto G72', categorie: 'Phone' },
  { id: 47, name: 'Oppo Find X6', categorie: 'Phone' },
  { id: 48, name: 'Oppo Reno 10', categorie: 'Phone' },
  { id: 49, name: 'Realme GT 3', categorie: 'Phone' },
  { id: 50, name: 'Vivo X90', categorie: 'Phone' },
  { id: 51, name: 'Lenovo Tab P11', categorie: 'Tablet' },
  { id: 52, name: 'Lenovo Yoga Tab 13', categorie: 'Tablet' },
  { id: 53, name: 'Microsoft Surface Pro 9', categorie: 'Tablet' },
  { id: 54, name: 'Microsoft Surface Go 3', categorie: 'Tablet' },
  { id: 55, name: 'Amazon Fire HD 10', categorie: 'Tablet' },
  { id: 56, name: 'Amazon Fire 7', categorie: 'Tablet' },
  { id: 57, name: 'Huawei MatePad 11', categorie: 'Tablet' },
  { id: 58, name: 'Huawei MatePad Pro', categorie: 'Tablet' },
  { id: 59, name: 'Samsung Galaxy Tab S7', categorie: 'Tablet' },
  { id: 60, name: 'Samsung Galaxy Tab S6 Lite', categorie: 'Tablet' },
  { id: 61, name: 'HP Spectre x360', categorie: 'Laptop' },
  { id: 62, name: 'HP Envy 15', categorie: 'Laptop' },
  { id: 63, name: 'Lenovo ThinkPad X1', categorie: 'Laptop' },
  { id: 64, name: 'Lenovo IdeaPad 5', categorie: 'Laptop' },
  { id: 65, name: 'Acer Swift 3', categorie: 'Laptop' },
  { id: 66, name: 'Acer Predator Helios', categorie: 'Laptop' },
  { id: 67, name: 'Razer Blade 15', categorie: 'Laptop' },
  { id: 68, name: 'Razer Blade 17', categorie: 'Laptop' },
  { id: 69, name: 'Asus TUF Gaming F15', categorie: 'Laptop' },
  { id: 70, name: 'Dell G15', categorie: 'Laptop' },
  { id: 71, name: 'Dell Alienware M15', categorie: 'Laptop' },
  { id: 72, name: 'MSI Stealth 15M', categorie: 'Laptop' },
  { id: 73, name: 'MSI Titan GT77', categorie: 'Laptop' },
  { id: 74, name: 'Apple MacBook Pro 16', categorie: 'Laptop' },
  { id: 75, name: 'Apple MacBook Air M1', categorie: 'Laptop' },
  { id: 76, name: 'Samsung The Frame 65"', categorie: 'TV' },
  { id: 77, name: 'Sony X90K 75"', categorie: 'TV' },
  { id: 78, name: 'LG UHD 50"', categorie: 'TV' },
  { id: 79, name: 'Hisense U8H 55"', categorie: 'TV' },
  { id: 80, name: 'TCL 5-Series 55"', categorie: 'TV' },
  { id: 81, name: 'Panasonic JZ2000 65"', categorie: 'TV' },
  { id: 82, name: 'Philips OLED+ 55"', categorie: 'TV' },
  { id: 83, name: 'Vizio M-Series 50"', categorie: 'TV' },
  { id: 84, name: 'Sharp AQUOS 60"', categorie: 'TV' },
  { id: 85, name: 'Samsung QN90B 75"', categorie: 'TV' },
  { id: 86, name: 'Fujifilm X-T5', categorie: 'Camera' },
  { id: 87, name: 'Fujifilm X-H2', categorie: 'Camera' },
  { id: 88, name: 'Panasonic Lumix GH6', categorie: 'Camera' },
  { id: 89, name: 'Olympus OM-D E-M10', categorie: 'Camera' },
  { id: 90, name: 'Leica Q2', categorie: 'Camera' },
  { id: 91, name: 'Bang & Olufsen Beoplay H95', categorie: 'Audio' },
  { id: 92, name: 'Sennheiser Momentum 4', categorie: 'Audio' },
  { id: 93, name: 'Sony SRS-XB33', categorie: 'Audio' },
  { id: 94, name: 'JBL PartyBox 310', categorie: 'Audio' },
  { id: 95, name: 'Marshall Stanmore II', categorie: 'Audio' },
  { id: 96, name: 'Apple Watch Series 8', categorie: 'Smartwatch' },
  { id: 97, name: 'Samsung Galaxy Watch 5', categorie: 'Smartwatch' },
  { id: 98, name: 'Garmin Fenix 7', categorie: 'Smartwatch' },
  { id: 99, name: 'Nintendo Switch OLED', categorie: 'Gaming console' },
  { id: 100, name: 'PlayStation 5', categorie: 'Gaming console' },
]